### ISSUE TITLE
Timed out waiting for worker process collecting filesystem usage to complete.

### ISSUE THREAD

**Issue by benofben** [cloud-partners/oci-cloudera#16]
I keep getting this:

`[01/Nov/2018 18:49:37 +0000] 48117 Monitor-HostMonitor throttling_logger ERROR    Timed out waiting for worker process collecting filesystem usage to complete. This may occur if the host has an NFS or other remote filesystem that is not responding to requests in a timely fashion. Current nodev filesystems: /dev/shm,/run,/sys/fs/cgroup,/run/user/0,/run/cloudera-scm-agent/process,/run/cloudera-scm-agent/process,/run/user/1000`

**Comment by benofben** [comment]
Trying with no disks.  Also trying on a clean cluster.

One theory, a missing trailing slash on the parcel repo might be causing an issue...

**Comment by benofben** [comment]
So, it's not the disks...

`[01/Nov/2018 19:33:43 +0000] 13492 Monitor-HostMonitor throttling_logger ERROR    Timed out waiting for worker process collecting filesystem usage to complete. This may occur if the host has an NFS or other remote filesystem that is not responding to requests in a timely fashion. Current nodev filesystems: /dev/shm,/run,/sys/fs/cgroup,/run/user/1000,/run/cloudera-scm-agent/process,/run/cloudera-scm-agent/process
`

**Comment by benofben** [comment]
closing this as it's a cm_api issue and we're moving to cm_client.

**Comment by boddiguo** [comment]
@benofben I met the same problem, can you talk about the solution please?
